// =============================================================================
// Copyright 2011-2020 Martin Törnqvist <m.tornq@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later
// =============================================================================

#ifndef GFX_HPP
#define GFX_HPP

#include <string>
#include <unordered_map>

struct P;

// NOTE: When updating this, also update the two maps below
enum class TileId {
        aim_marker_head,
        aim_marker_line,
        alchemist_bench_empty,
        alchemist_bench_full,
        altar,
        gong,
        ammo,
        amoeba,
        amulet,
        ape,
        armor,
        axe,
        barrel,
        bat,
        blast1,
        blast2,
        bog_tcher,
        bookshelf_empty,
        bookshelf_full,
        brain,
        brazier,
        bush,
        byakhee,
        cabinet_closed,
        cabinet_open,
        cave_wall_front,
        cave_wall_top,
        chains,
        chest_closed,
        chest_open,
        chthonian,
        church_bench,
        clockwork,
        club,
        cocoon_closed,
        cocoon_open,
        corpse,
        corpse2,
        crawling_hand,
        crawling_intestines,
        croc_head_mummy,
        crowbar,
        crystal,
        cultist_dagger,
        cultist_firearm,
        cultist_spiked_mace,
        dagger,
        deep_one,
        device1,
        device2,
        door_broken,
        door_closed,
        door_open,
        dynamite,
        dynamite_lit,
        egypt_wall_front,
        egypt_wall_top,
        elder_sign,
        excl_mark,
        fiend,
        flare,
        flare_gun,
        flare_lit,
        floating_skull,
        floor,
        fountain,
        fungi,
        gas_mask,
        gas_spore,
        gate_closed,
        gate_open,
        ghost,
        ghoul,
        giant_spider,
        gore1,
        gore2,
        gore3,
        gore4,
        gore5,
        gore6,
        gore7,
        gore8,
        grate,
        grave_stone,
        hammer,
        hangbridge_hor,
        hangbridge_ver,
        heart,
        horn,
        hound,
        hunting_horror,
        incinerator,
        iron_spike,
        khaga,
        lantern,
        leech,
        leng_elder,
        lever_left,
        lever_right,
        lockpick,
        locust,
        machete,
        mantis,
        mass_of_worms,
        medical_bag,
        mi_go,
        mi_go_armor,
        mi_go_gun,
        molotov,
        monolith,
        mummy,
        ooze,
        orb,
        phantasm,
        pharaoh_staff,
        pillar,
        pillar_broken,
        pillar_carved,
        pistol,
        revolver,
        rifle,
        pit,
        pitchfork,
        player_firearm,
        player_melee,
        polyp,
        potion,
        projectile_std_back_slash,
        projectile_std_dash,
        projectile_std_front_slash,
        projectile_std_vertical_bar,
        pylon,
        rat,
        rat_thing,
        raven,
        ring,
        rock,
        rod,
        rubble_high,
        rubble_low,
        sarcophagus,
        scorched_ground,
        scroll,
        shadow,
        shotgun,
        sledge_hammer,
        smoke,
        snake,
        spider,
        spiked_mace,
        spirit,
        square_checkered,
        square_checkered_sparse,
        stairs_down,
        stalagmite,
        stopwatch,
        tentacles,
        the_high_priest,
        tomb_closed,
        tomb_open,
        tommy_gun,
        trap_general,
        trapez,
        tree,
        tree_fungi,
        vines,
        void_traveler,
        vortex,
        wall_front,
        wall_front_alt1,
        wall_front_alt2,
        wall_top,
        water,
        web,
        weight,
        witch_or_warlock,
        wolf,
        wraith,
        zombie_armed,
        zombie_bloated,
        zombie_dust,
        zombie_unarmed,

        END
};

// TODO: Define in cpp file instead
const std::unordered_map<std::string, TileId> g_str_to_tile_id_map = {
        {"aim_marker_head", TileId::aim_marker_head},
        {"aim_marker_line", TileId::aim_marker_line},
        {"alchemist_bench_empty", TileId::alchemist_bench_empty},
        {"alchemist_bench_full", TileId::alchemist_bench_full},
        {"altar", TileId::altar},
        {"gong", TileId::gong},
        {"ammo", TileId::ammo},
        {"amoeba", TileId::amoeba},
        {"amulet", TileId::amulet},
        {"ape", TileId::ape},
        {"armor", TileId::armor},
        {"axe", TileId::axe},
        {"barrel", TileId::barrel},
        {"bat", TileId::bat},
        {"blast1", TileId::blast1},
        {"blast2", TileId::blast2},
        {"bog_tcher", TileId::bog_tcher},
        {"bookshelf_empty", TileId::bookshelf_empty},
        {"bookshelf_full", TileId::bookshelf_full},
        {"brain", TileId::brain},
        {"brazier", TileId::brazier},
        {"bush", TileId::bush},
        {"byakhee", TileId::byakhee},
        {"cabinet_closed", TileId::cabinet_closed},
        {"cabinet_open", TileId::cabinet_open},
        {"cave_wall_front", TileId::cave_wall_front},
        {"cave_wall_top", TileId::cave_wall_top},
        {"chains", TileId::chains},
        {"chest_closed", TileId::chest_closed},
        {"chest_open", TileId::chest_open},
        {"chthonian", TileId::chthonian},
        {"church_bench", TileId::church_bench},
        {"clockwork", TileId::clockwork},
        {"club", TileId::club},
        {"cocoon_closed", TileId::cocoon_closed},
        {"cocoon_open", TileId::cocoon_open},
        {"corpse", TileId::corpse},
        {"corpse2", TileId::corpse2},
        {"crawling_hand", TileId::crawling_hand},
        {"crawling_intestines", TileId::crawling_intestines},
        {"croc_head_mummy", TileId::croc_head_mummy},
        {"crowbar", TileId::crowbar},
        {"crystal", TileId::crystal},
        {"cultist_dagger", TileId::cultist_dagger},
        {"cultist_firearm", TileId::cultist_firearm},
        {"cultist_spiked_mace", TileId::cultist_spiked_mace},
        {"dagger", TileId::dagger},
        {"deep_one", TileId::deep_one},
        {"device1", TileId::device1},
        {"device2", TileId::device2},
        {"door_broken", TileId::door_broken},
        {"door_closed", TileId::door_closed},
        {"door_open", TileId::door_open},
        {"dynamite", TileId::dynamite},
        {"dynamite_lit", TileId::dynamite_lit},
        {"egypt_wall_front", TileId::egypt_wall_front},
        {"egypt_wall_top", TileId::egypt_wall_top},
        {"elder_sign", TileId::elder_sign},
        {"excl_mark", TileId::excl_mark},
        {"fiend", TileId::fiend},
        {"flare", TileId::flare},
        {"flare_gun", TileId::flare_gun},
        {"flare_lit", TileId::flare_lit},
        {"floating_skull", TileId::floating_skull},
        {"floor", TileId::floor},
        {"fountain", TileId::fountain},
        {"fungi", TileId::fungi},
        {"gas_mask", TileId::gas_mask},
        {"gas_spore", TileId::gas_spore},
        {"gate_closed", TileId::gate_closed},
        {"gate_open", TileId::gate_open},
        {"ghost", TileId::ghost},
        {"ghoul", TileId::ghoul},
        {"giant_spider", TileId::giant_spider},
        {"gore1", TileId::gore1},
        {"gore2", TileId::gore2},
        {"gore3", TileId::gore3},
        {"gore4", TileId::gore4},
        {"gore5", TileId::gore5},
        {"gore6", TileId::gore6},
        {"gore7", TileId::gore7},
        {"gore8", TileId::gore8},
        {"grate", TileId::grate},
        {"grave_stone", TileId::grave_stone},
        {"hammer", TileId::hammer},
        {"hangbridge_hor", TileId::hangbridge_hor},
        {"hangbridge_ver", TileId::hangbridge_ver},
        {"heart", TileId::heart},
        {"horn", TileId::horn},
        {"hound", TileId::hound},
        {"hunting_horror", TileId::hunting_horror},
        {"incinerator", TileId::incinerator},
        {"iron_spike", TileId::iron_spike},
        {"khaga", TileId::khaga},
        {"lantern", TileId::lantern},
        {"leech", TileId::leech},
        {"leng_elder", TileId::leng_elder},
        {"lever_left", TileId::lever_left},
        {"lever_right", TileId::lever_right},
        {"lockpick", TileId::lockpick},
        {"locust", TileId::locust},
        {"machete", TileId::machete},
        {"mantis", TileId::mantis},
        {"mass_of_worms", TileId::mass_of_worms},
        {"medical_bag", TileId::medical_bag},
        {"mi_go", TileId::mi_go},
        {"mi_go_armor", TileId::mi_go_armor},
        {"mi_go_gun", TileId::mi_go_gun},
        {"molotov", TileId::molotov},
        {"monolith", TileId::monolith},
        {"mummy", TileId::mummy},
        {"ooze", TileId::ooze},
        {"orb", TileId::orb},
        {"phantasm", TileId::phantasm},
        {"pharaoh_staff", TileId::pharaoh_staff},
        {"pillar", TileId::pillar},
        {"pillar_broken", TileId::pillar_broken},
        {"pillar_carved", TileId::pillar_carved},
        {"pistol", TileId::pistol},
        {"revolver", TileId::revolver},
        {"rifle", TileId::rifle},
        {"pit", TileId::pit},
        {"pitchfork", TileId::pitchfork},
        {"player_firearm", TileId::player_firearm},
        {"player_melee", TileId::player_melee},
        {"polyp", TileId::polyp},
        {"potion", TileId::potion},
        {"projectile_std_back_slash", TileId::projectile_std_back_slash},
        {"projectile_std_dash", TileId::projectile_std_dash},
        {"projectile_std_front_slash", TileId::projectile_std_front_slash},
        {"projectile_std_vertical_bar", TileId::projectile_std_vertical_bar},
        {"pylon", TileId::pylon},
        {"rat", TileId::rat},
        {"rat_thing", TileId::rat_thing},
        {"raven", TileId::raven},
        {"ring", TileId::ring},
        {"rock", TileId::rock},
        {"rod", TileId::rod},
        {"rubble_high", TileId::rubble_high},
        {"rubble_low", TileId::rubble_low},
        {"sarcophagus", TileId::sarcophagus},
        {"scorched_ground", TileId::scorched_ground},
        {"scroll", TileId::scroll},
        {"shadow", TileId::shadow},
        {"shotgun", TileId::shotgun},
        {"sledge_hammer", TileId::sledge_hammer},
        {"smoke", TileId::smoke},
        {"snake", TileId::snake},
        {"spider", TileId::spider},
        {"spiked_mace", TileId::spiked_mace},
        {"spirit", TileId::spirit},
        {"square_checkered", TileId::square_checkered},
        {"square_checkered_sparse", TileId::square_checkered_sparse},
        {"stairs_down", TileId::stairs_down},
        {"stalagmite", TileId::stalagmite},
        {"stopwatch", TileId::stopwatch},
        {"tentacles", TileId::tentacles},
        {"the_high_priest", TileId::the_high_priest},
        {"tomb_closed", TileId::tomb_closed},
        {"tomb_open", TileId::tomb_open},
        {"tommy_gun", TileId::tommy_gun},
        {"trap_general", TileId::trap_general},
        {"trapez", TileId::trapez},
        {"tree", TileId::tree},
        {"tree_fungi", TileId::tree_fungi},
        {"vines", TileId::vines},
        {"void_traveler", TileId::void_traveler},
        {"vortex", TileId::vortex},
        {"wall_front", TileId::wall_front},
        {"wall_front_alt1", TileId::wall_front_alt1},
        {"wall_front_alt2", TileId::wall_front_alt2},
        {"wall_top", TileId::wall_top},
        {"water", TileId::water},
        {"web", TileId::web},
        {"weight", TileId::weight},
        {"witch_or_warlock", TileId::witch_or_warlock},
        {"wolf", TileId::wolf},
        {"wraith", TileId::wraith},
        {"zombie_armed", TileId::zombie_armed},
        {"zombie_bloated", TileId::zombie_bloated},
        {"zombie_dust", TileId::zombie_dust},
        {"zombie_unarmed", TileId::zombie_unarmed},
        {"none", TileId::END}};

// TODO: Define in cpp file instead
const std::unordered_map<TileId, std::string> g_tile_id_to_str_map = {
        {TileId::aim_marker_head, "aim_marker_head"},
        {TileId::aim_marker_line, "aim_marker_line"},
        {TileId::alchemist_bench_empty, "alchemist_bench_empty"},
        {TileId::alchemist_bench_full, "alchemist_bench_full"},
        {TileId::altar, "altar"},
        {TileId::gong, "gong"},
        {TileId::ammo, "ammo"},
        {TileId::amoeba, "amoeba"},
        {TileId::amulet, "amulet"},
        {TileId::ape, "ape"},
        {TileId::armor, "armor"},
        {TileId::axe, "axe"},
        {TileId::barrel, "barrel"},
        {TileId::bat, "bat"},
        {TileId::blast1, "blast1"},
        {TileId::blast2, "blast2"},
        {TileId::bog_tcher, "bog_tcher"},
        {TileId::bookshelf_empty, "bookshelf_empty"},
        {TileId::bookshelf_full, "bookshelf_full"},
        {TileId::brain, "brain"},
        {TileId::brazier, "brazier"},
        {TileId::bush, "bush"},
        {TileId::byakhee, "byakhee"},
        {TileId::cabinet_closed, "cabinet_closed"},
        {TileId::cabinet_open, "cabinet_open"},
        {TileId::cave_wall_front, "cave_wall_front"},
        {TileId::cave_wall_top, "cave_wall_top"},
        {TileId::chains, "chains"},
        {TileId::chest_closed, "chest_closed"},
        {TileId::chest_open, "chest_open"},
        {TileId::chthonian, "chthonian"},
        {TileId::church_bench, "church_bench"},
        {TileId::clockwork, "clockwork"},
        {TileId::club, "club"},
        {TileId::cocoon_closed, "cocoon_closed"},
        {TileId::cocoon_open, "cocoon_open"},
        {TileId::corpse, "corpse"},
        {TileId::corpse2, "corpse2"},
        {TileId::crawling_hand, "crawling_hand"},
        {TileId::crawling_intestines, "crawling_intestines"},
        {TileId::croc_head_mummy, "croc_head_mummy"},
        {TileId::crowbar, "crowbar"},
        {TileId::crystal, "crystal"},
        {TileId::cultist_dagger, "cultist_dagger"},
        {TileId::cultist_firearm, "cultist_firearm"},
        {TileId::cultist_spiked_mace, "cultist_spiked_mace"},
        {TileId::dagger, "dagger"},
        {TileId::deep_one, "deep_one"},
        {TileId::device1, "device1"},
        {TileId::device2, "device2"},
        {TileId::door_broken, "door_broken"},
        {TileId::door_closed, "door_closed"},
        {TileId::door_open, "door_open"},
        {TileId::dynamite, "dynamite"},
        {TileId::dynamite_lit, "dynamite_lit"},
        {TileId::egypt_wall_front, "egypt_wall_front"},
        {TileId::egypt_wall_top, "egypt_wall_top"},
        {TileId::elder_sign, "elder_sign"},
        {TileId::excl_mark, "excl_mark"},
        {TileId::fiend, "fiend"},
        {TileId::flare, "flare"},
        {TileId::flare_gun, "flare_gun"},
        {TileId::flare_lit, "flare_lit"},
        {TileId::floating_skull, "floating_skull"},
        {TileId::floor, "floor"},
        {TileId::fountain, "fountain"},
        {TileId::fungi, "fungi"},
        {TileId::gas_mask, "gas_mask"},
        {TileId::gas_spore, "gas_spore"},
        {TileId::gate_closed, "gate_closed"},
        {TileId::gate_open, "gate_open"},
        {TileId::ghost, "ghost"},
        {TileId::ghoul, "ghoul"},
        {TileId::giant_spider, "giant_spider"},
        {TileId::gore1, "gore1"},
        {TileId::gore2, "gore2"},
        {TileId::gore3, "gore3"},
        {TileId::gore4, "gore4"},
        {TileId::gore5, "gore5"},
        {TileId::gore6, "gore6"},
        {TileId::gore7, "gore7"},
        {TileId::gore8, "gore8"},
        {TileId::grate, "grate"},
        {TileId::grave_stone, "grave_stone"},
        {TileId::hammer, "hammer"},
        {TileId::hangbridge_hor, "hangbridge_hor"},
        {TileId::hangbridge_ver, "hangbridge_ver"},
        {TileId::heart, "heart"},
        {TileId::horn, "horn"},
        {TileId::hound, "hound"},
        {TileId::hunting_horror, "hunting_horror"},
        {TileId::incinerator, "incinerator"},
        {TileId::iron_spike, "iron_spike"},
        {TileId::khaga, "khaga"},
        {TileId::lantern, "lantern"},
        {TileId::leech, "leech"},
        {TileId::leng_elder, "leng_elder"},
        {TileId::lever_left, "lever_left"},
        {TileId::lever_right, "lever_right"},
        {TileId::lockpick, "lockpick"},
        {TileId::locust, "locust"},
        {TileId::machete, "machete"},
        {TileId::mantis, "mantis"},
        {TileId::mass_of_worms, "mass_of_worms"},
        {TileId::medical_bag, "medical_bag"},
        {TileId::mi_go, "mi_go"},
        {TileId::mi_go_armor, "mi_go_armor"},
        {TileId::mi_go_gun, "mi_go_gun"},
        {TileId::molotov, "molotov"},
        {TileId::monolith, "monolith"},
        {TileId::mummy, "mummy"},
        {TileId::ooze, "ooze"},
        {TileId::orb, "orb"},
        {TileId::phantasm, "phantasm"},
        {TileId::pharaoh_staff, "pharaoh_staff"},
        {TileId::pillar, "pillar"},
        {TileId::pillar_broken, "pillar_broken"},
        {TileId::pillar_carved, "pillar_carved"},
        {TileId::pistol, "pistol"},
        {TileId::revolver, "revolver"},
        {TileId::rifle, "rifle"},
        {TileId::pit, "pit"},
        {TileId::pitchfork, "pitchfork"},
        {TileId::player_firearm, "player_firearm"},
        {TileId::player_melee, "player_melee"},
        {TileId::polyp, "polyp"},
        {TileId::potion, "potion"},
        {TileId::projectile_std_back_slash, "projectile_std_back_slash"},
        {TileId::projectile_std_dash, "projectile_std_dash"},
        {TileId::projectile_std_front_slash, "projectile_std_front_slash"},
        {TileId::projectile_std_vertical_bar, "projectile_std_vertical_bar"},
        {TileId::pylon, "pylon"},
        {TileId::rat, "rat"},
        {TileId::rat_thing, "rat_thing"},
        {TileId::raven, "raven"},
        {TileId::ring, "ring"},
        {TileId::rock, "rock"},
        {TileId::rod, "rod"},
        {TileId::rubble_high, "rubble_high"},
        {TileId::rubble_low, "rubble_low"},
        {TileId::sarcophagus, "sarcophagus"},
        {TileId::scorched_ground, "scorched_ground"},
        {TileId::scroll, "scroll"},
        {TileId::shadow, "shadow"},
        {TileId::shotgun, "shotgun"},
        {TileId::sledge_hammer, "sledge_hammer"},
        {TileId::smoke, "smoke"},
        {TileId::snake, "snake"},
        {TileId::spider, "spider"},
        {TileId::spiked_mace, "spiked_mace"},
        {TileId::spirit, "spirit"},
        {TileId::square_checkered, "square_checkered"},
        {TileId::square_checkered_sparse, "square_checkered_sparse"},
        {TileId::stairs_down, "stairs_down"},
        {TileId::stalagmite, "stalagmite"},
        {TileId::stopwatch, "stopwatch"},
        {TileId::tentacles, "tentacles"},
        {TileId::the_high_priest, "the_high_priest"},
        {TileId::tomb_closed, "tomb_closed"},
        {TileId::tomb_open, "tomb_open"},
        {TileId::tommy_gun, "tommy_gun"},
        {TileId::trap_general, "trap_general"},
        {TileId::trapez, "trapez"},
        {TileId::tree, "tree"},
        {TileId::tree_fungi, "tree_fungi"},
        {TileId::vines, "vines"},
        {TileId::void_traveler, "void_traveler"},
        {TileId::vortex, "vortex"},
        {TileId::wall_front, "wall_front"},
        {TileId::wall_front_alt1, "wall_front_alt1"},
        {TileId::wall_front_alt2, "wall_front_alt2"},
        {TileId::wall_top, "wall_top"},
        {TileId::water, "water"},
        {TileId::web, "web"},
        {TileId::weight, "weight"},
        {TileId::witch_or_warlock, "witch_or_warlock"},
        {TileId::wolf, "wolf"},
        {TileId::wraith, "wraith"},
        {TileId::zombie_armed, "zombie_armed"},
        {TileId::zombie_bloated, "zombie_bloated"},
        {TileId::zombie_dust, "zombie_dust"},
        {TileId::zombie_unarmed, "zombie_unarmed"},
        {TileId::END, "none"}};

namespace gfx {

P character_pos(char character);

} // namespace gfx

#endif // GFX_HPP
